name: saunatonttu
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  intl:
  flutter_bloc:
  bloc_concurrency:
  graphql:
  jwt_decoder:
  hive_flutter:
  formz:
  animations:
  google_sign_in:
  geolocator:
  geofencing:
    path: ../FlutterGeofencing
  stream_transform:
  flutter_local_notifications: 13.0.0
  cached_network_image:
  photo_view:
  map:
  numberpicker: ^2.1.1
  equatable:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  json_serializable:
  build_runner:
  graphql_codegen:
  flutter_launcher_icons:

flutter:
  uses-material-design: true

  assets:
    - assets/images/sign_in_with_google.png
    - assets/images/saunatonttu.png
    - assets/images/default_user.png
    - assets/images/dot_pinlet-2-medium.png

flutter_icons:
  image_path: "assets/images/saunatonttu.png"
  android: "launcher_icon"
