// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using NpgsqlTypes;
using SaunatonttuAPI;
using SaunatonttuAPI.Sauna.Entity;

#nullable disable

namespace SaunatonttuAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230211091112_v23")]
    partial class v23
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "sauna_user_kind", new[] { "owner", "staff", "guest" });
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SaunatonttuAPI.Attribute.Entity.Attribute", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("icon");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_attribute");

                    b.ToTable("attribute", (string)null);
                });

            modelBuilder.Entity("SaunatonttuAPI.OpeningHours.Entity.OpeningHour", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly?>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("integer")
                        .HasColumnName("day_of_week");

                    b.Property<bool>("IsOpening")
                        .HasColumnType("boolean")
                        .HasColumnName("is_opening");

                    b.Property<string>("Label")
                        .HasColumnType("text")
                        .HasColumnName("label");

                    b.Property<int>("SaunaId")
                        .HasColumnType("integer")
                        .HasColumnName("sauna_id");

                    b.Property<TimeOnly>("Time")
                        .HasColumnType("time without time zone")
                        .HasColumnName("time");

                    b.HasKey("Id")
                        .HasName("pk_opening_hour");

                    b.HasIndex("SaunaId")
                        .HasDatabaseName("ix_opening_hour_sauna_id");

                    b.ToTable("opening_hour", (string)null);
                });

            modelBuilder.Entity("SaunatonttuAPI.Picture.Entity.Picture", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FullSizeUrl")
                        .IsRequired()
                        .HasMaxLength(768)
                        .HasColumnType("character varying(768)")
                        .HasColumnName("full_size_url");

                    b.Property<string>("ThumbnailUrl")
                        .IsRequired()
                        .HasMaxLength(768)
                        .HasColumnType("character varying(768)")
                        .HasColumnName("thumbnail_url");

                    b.HasKey("Id")
                        .HasName("pk_picture");

                    b.ToTable("picture", (string)null);
                });

            modelBuilder.Entity("SaunatonttuAPI.Price.Entity.Currency", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.Property<float>("DollarRatio")
                        .HasColumnType("real")
                        .HasColumnName("dollar_ratio");

                    b.HasKey("Id")
                        .HasName("pk_currency");

                    b.ToTable("currency", (string)null);
                });

            modelBuilder.Entity("SaunatonttuAPI.Price.Entity.Price", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CurrencyId")
                        .HasColumnType("integer")
                        .HasColumnName("currency_id");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("label");

                    b.Property<decimal>("Value")
                        .HasColumnType("money")
                        .HasColumnName("value");

                    b.HasKey("Id")
                        .HasName("pk_price");

                    b.HasIndex("CurrencyId")
                        .HasDatabaseName("ix_price_currency_id");

                    b.ToTable("price", (string)null);
                });

            modelBuilder.Entity("SaunatonttuAPI.Report.Entity.Report", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AuthorId")
                        .HasColumnType("integer")
                        .HasColumnName("author_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("message");

                    b.Property<string>("Result")
                        .HasColumnType("text")
                        .HasColumnName("result");

                    b.Property<int>("SubjectId")
                        .HasColumnType("integer")
                        .HasColumnName("subject_id");

                    b.Property<string>("SubjectName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("subject_name");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_report");

                    b.HasIndex("AuthorId")
                        .HasDatabaseName("ix_report_author_id");

                    b.ToTable("report", (string)null);
                });

            modelBuilder.Entity("SaunatonttuAPI.Sauna.Entity.Sauna", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("text")
                        .HasColumnName("address");

                    b.Property<string>("Content")
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<string>("Email")
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("GoogleId")
                        .HasColumnType("text")
                        .HasColumnName("google_id");

                    b.Property<string>("GooglePlaceDetailResponse")
                        .HasColumnType("text")
                        .HasColumnName("google_place_detail_response");

                    b.Property<bool>("IsPrivate")
                        .HasColumnType("boolean")
                        .HasColumnName("is_private");

                    b.Property<DateTime?>("LastGoogleUpdate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_google_update");

                    b.Property<string>("LeadParagraph")
                        .HasColumnType("text")
                        .HasColumnName("lead_paragraph");

                    b.Property<Point>("Location")
                        .IsRequired()
                        .HasColumnType("geometry")
                        .HasColumnName("location");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Phone")
                        .HasColumnType("text")
                        .HasColumnName("phone");

                    b.Property<NpgsqlTsVector>("SearchVector")
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("tsvector")
                        .HasColumnName("search_vector")
                        .HasComputedColumnSql("to_tsvector('simple', coalesce(\"name\", '') || ' ' || coalesce(\"email\", '') || ' ' || coalesce(\"lead_paragraph\", '') || ' ' || coalesce(\"content\", '') || ' ' || coalesce(\"phone\", ''))", true);

                    b.Property<string>("Url")
                        .HasColumnType("text")
                        .HasColumnName("url");

                    b.HasKey("Id")
                        .HasName("pk_sauna");

                    b.HasIndex("SearchVector")
                        .HasDatabaseName("ix_sauna_search_vector");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("SearchVector"), "GIN");

                    b.ToTable("sauna", (string)null);
                });

            modelBuilder.Entity("SaunatonttuAPI.Sauna.Entity.SaunaAttribute", b =>
                {
                    b.Property<int>("SaunaId")
                        .HasColumnType("integer")
                        .HasColumnName("sauna_id");

                    b.Property<int>("AttributeId")
                        .HasColumnType("integer")
                        .HasColumnName("attribute_id");

                    b.HasKey("SaunaId", "AttributeId")
                        .HasName("pk_sauna_attribute");

                    b.HasIndex("AttributeId")
                        .HasDatabaseName("ix_sauna_attribute_attribute_id");

                    b.ToTable("sauna_attribute", (string)null);
                });

            modelBuilder.Entity("SaunatonttuAPI.Sauna.Entity.SaunaPicture", b =>
                {
                    b.Property<int>("SaunaId")
                        .HasColumnType("integer")
                        .HasColumnName("sauna_id");

                    b.Property<int>("PictureId")
                        .HasColumnType("integer")
                        .HasColumnName("picture_id");

                    b.HasKey("SaunaId", "PictureId")
                        .HasName("pk_sauna_picture");

                    b.HasIndex("PictureId")
                        .HasDatabaseName("ix_sauna_picture_picture_id");

                    b.ToTable("sauna_picture", (string)null);
                });

            modelBuilder.Entity("SaunatonttuAPI.Sauna.Entity.SaunaPrice", b =>
                {
                    b.Property<int>("SaunaId")
                        .HasColumnType("integer")
                        .HasColumnName("sauna_id");

                    b.Property<int>("PriceId")
                        .HasColumnType("integer")
                        .HasColumnName("price_id");

                    b.HasKey("SaunaId", "PriceId")
                        .HasName("pk_sauna_price");

                    b.HasIndex("PriceId")
                        .HasDatabaseName("ix_sauna_price_price_id");

                    b.ToTable("sauna_price", (string)null);
                });

            modelBuilder.Entity("SaunatonttuAPI.Sauna.Entity.SaunaUser", b =>
                {
                    b.Property<int>("SaunaId")
                        .HasColumnType("integer")
                        .HasColumnName("sauna_id");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.Property<SaunaUserKind>("Kind")
                        .HasColumnType("sauna_user_kind")
                        .HasColumnName("kind");

                    b.HasKey("SaunaId", "UserId")
                        .HasName("pk_sauna_user");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_sauna_user_user_id");

                    b.ToTable("sauna_user", (string)null);
                });

            modelBuilder.Entity("SaunatonttuAPI.Scraping.Entity.ResponseLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ReceivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("received_at");

                    b.Property<string>("RequestUid")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("request_uid");

                    b.Property<string>("Response")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("response");

                    b.HasKey("Id")
                        .HasName("pk_response_log");

                    b.ToTable("response_log", (string)null);
                });

            modelBuilder.Entity("SaunatonttuAPI.Scraping.Entity.TextSearchRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("city");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision")
                        .HasColumnName("latitude");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision")
                        .HasColumnName("longitude");

                    b.Property<double>("Radius")
                        .HasColumnType("double precision")
                        .HasColumnName("radius");

                    b.Property<DateTime?>("ScrapedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("scraped_at");

                    b.HasKey("Id")
                        .HasName("pk_text_search_request");

                    b.ToTable("text_search_request", (string)null);
                });

            modelBuilder.Entity("SaunatonttuAPI.User.Entity.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("text")
                        .HasColumnName("avatar_url");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Password")
                        .HasColumnType("text")
                        .HasColumnName("password");

                    b.HasKey("Id")
                        .HasName("pk_user");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_user_email");

                    b.ToTable("user", (string)null);
                });

            modelBuilder.Entity("SaunatonttuAPI.VisitHistory.Entity.VisitHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Note")
                        .HasColumnType("text")
                        .HasColumnName("note");

                    b.Property<int>("SaunaId")
                        .HasColumnType("integer")
                        .HasColumnName("sauna_id");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.Property<int>("VisitDuration")
                        .HasColumnType("integer")
                        .HasColumnName("visit_duration");

                    b.Property<DateTime>("VisitedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("visited_at");

                    b.HasKey("Id")
                        .HasName("pk_visit_history");

                    b.HasIndex("SaunaId")
                        .HasDatabaseName("ix_visit_history_sauna_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_visit_history_user_id");

                    b.ToTable("visit_history", (string)null);
                });

            modelBuilder.Entity("SaunatonttuAPI.OpeningHours.Entity.OpeningHour", b =>
                {
                    b.HasOne("SaunatonttuAPI.Sauna.Entity.Sauna", "Sauna")
                        .WithMany("OpeningHours")
                        .HasForeignKey("SaunaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_opening_hour_sauna_sauna_id");

                    b.Navigation("Sauna");
                });

            modelBuilder.Entity("SaunatonttuAPI.Price.Entity.Price", b =>
                {
                    b.HasOne("SaunatonttuAPI.Price.Entity.Currency", "Currency")
                        .WithMany()
                        .HasForeignKey("CurrencyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_price_currency_currency_id");

                    b.Navigation("Currency");
                });

            modelBuilder.Entity("SaunatonttuAPI.Report.Entity.Report", b =>
                {
                    b.HasOne("SaunatonttuAPI.User.Entity.User", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_report_user_author_id");

                    b.Navigation("Author");
                });

            modelBuilder.Entity("SaunatonttuAPI.Sauna.Entity.SaunaAttribute", b =>
                {
                    b.HasOne("SaunatonttuAPI.Attribute.Entity.Attribute", "Attribute")
                        .WithMany()
                        .HasForeignKey("AttributeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_sauna_attribute_attribute_attribute_id");

                    b.HasOne("SaunatonttuAPI.Sauna.Entity.Sauna", "Sauna")
                        .WithMany("SaunaAttributes")
                        .HasForeignKey("SaunaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_sauna_attribute_sauna_sauna_id");

                    b.Navigation("Attribute");

                    b.Navigation("Sauna");
                });

            modelBuilder.Entity("SaunatonttuAPI.Sauna.Entity.SaunaPicture", b =>
                {
                    b.HasOne("SaunatonttuAPI.Picture.Entity.Picture", "Picture")
                        .WithMany()
                        .HasForeignKey("PictureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_sauna_picture_picture_picture_id");

                    b.HasOne("SaunatonttuAPI.Sauna.Entity.Sauna", "Sauna")
                        .WithMany("SaunaPicture")
                        .HasForeignKey("SaunaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_sauna_picture_sauna_sauna_id");

                    b.Navigation("Picture");

                    b.Navigation("Sauna");
                });

            modelBuilder.Entity("SaunatonttuAPI.Sauna.Entity.SaunaPrice", b =>
                {
                    b.HasOne("SaunatonttuAPI.Price.Entity.Price", "Price")
                        .WithMany()
                        .HasForeignKey("PriceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_sauna_price_price_price_id");

                    b.HasOne("SaunatonttuAPI.Sauna.Entity.Sauna", "Sauna")
                        .WithMany("SaunaPrices")
                        .HasForeignKey("SaunaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_sauna_price_sauna_sauna_id");

                    b.Navigation("Price");

                    b.Navigation("Sauna");
                });

            modelBuilder.Entity("SaunatonttuAPI.Sauna.Entity.SaunaUser", b =>
                {
                    b.HasOne("SaunatonttuAPI.Sauna.Entity.Sauna", "Sauna")
                        .WithMany("Users")
                        .HasForeignKey("SaunaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_sauna_user_sauna_sauna_id");

                    b.HasOne("SaunatonttuAPI.User.Entity.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_sauna_user_user_user_id");

                    b.Navigation("Sauna");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SaunatonttuAPI.VisitHistory.Entity.VisitHistory", b =>
                {
                    b.HasOne("SaunatonttuAPI.Sauna.Entity.Sauna", "Sauna")
                        .WithMany()
                        .HasForeignKey("SaunaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_visit_history_sauna_sauna_id");

                    b.HasOne("SaunatonttuAPI.User.Entity.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_visit_history_user_user_id");

                    b.Navigation("Sauna");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SaunatonttuAPI.Sauna.Entity.Sauna", b =>
                {
                    b.Navigation("OpeningHours");

                    b.Navigation("SaunaAttributes");

                    b.Navigation("SaunaPicture");

                    b.Navigation("SaunaPrices");

                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
